spring:
  application:
    name: Consumer
  cloud:
    function:
      definition: sendRiderLocation; sendRiderStatus
    stream:
      function:
        definition: processRiderLocation; processRiderStatus
      bindings:
        processRiderLocation-in-0:
          destination: my-location
        processRiderStatus-in-0:
          destination: my-location-status
    kafka:
      binder:
        brokers: localhost:9092


#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.springconsumer.RiderLocation

server:
  port: 8081
