spring:
  application:
    name: Producer
  cloud:
    function:
      definition: sendRiderLocation; sendRiderStatus
    stream:
      poller:
        fixed-delay: 5000
      function:
        definition: sendRiderLocation; sendRiderStatus
      bindings:
        sendRiderLocation-out-0:
          destination: my-new-topic
          content-type: application/json
        sendRiderStatus-out-0:
          destination: my-location-status
          content-type: application/json


      kafka:
        binder:
          brokers: localhost:9092


#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
#  cloud:
#    function:
#      defination: uppercase
#    function.web.path: /uppercase

